### ISSUE TITLE
iframe自适应问题

### ISSUE THREAD

**Issue by Burial0268** [newcdn/bilibili#11]
配置了iframe标签并且设置了自适应，手机端访问没有问题，ipad端访问会因为下方空间不够而重叠在一起

**Comment by Burial0268** [comment]
就像这样
![1](https://gbcl.imgcdn.zyglq.cn/2022-04-30/1651324356-576062-screenshot-2022-04-30-21-10-39-043-markvia.jpg)

**Comment by Jgckm** [comment]
## html 结构 
```html
 <div class="video-container video-ratio-16by9"> <iframe></iframe> </div>

```
## css结构
```css
.video-container { display: block; position: relative; width: 100%; height: 0; overflow: hidden; box-sizing: border-box } .video-container iframe, .video-container video { position: absolute; top: 0; left: 0; border: none; width: 100%; height: 100% } .video-ratio-16by9 { padding-bottom: 56.25% /* 9/16 */ } .video-ratio-4by3 { padding-bottom: 75% /* 3/4 */ }
```
### 以一个 16:9的影片来说  9 除以 16 等于 0.5625 ，也就是 56.25%。所以将 padding-bottom 设定为 56.25% 就能输出一个16:9 的容器 。 4:3的同理
希望可以帮助到你
